
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x91\x95\xa5\xf7\xe0^bz\xc0\xf4\x04\xf9Z\xebA\xba'
    
_lr_action_items = {'-':([0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[4,7,-10,-9,4,4,4,4,4,4,4,-7,-10,7,-4,-5,-3,-6,7,-8,]),'(':([0,4,6,7,8,9,10,11,],[6,6,6,6,6,6,6,6,]),'=':([2,],[11,]),'+':([1,2,3,12,13,14,15,16,17,18,19,20,],[9,-10,-9,-7,-10,9,-4,-5,-3,-6,9,-8,]),'NUMBER':([0,4,6,7,8,9,10,11,],[3,3,3,3,3,3,3,3,]),'NAME':([0,4,6,7,8,9,10,11,],[2,13,13,13,13,13,13,13,]),'/':([1,2,3,12,13,14,15,16,17,18,19,20,],[10,-10,-9,-7,-10,10,10,-5,10,-6,10,-8,]),'$end':([1,2,3,5,12,13,15,16,17,18,19,20,],[-2,-10,-9,0,-7,-10,-4,-5,-3,-6,-1,-8,]),'*':([1,2,3,12,13,14,15,16,17,18,19,20,],[8,-10,-9,-7,-10,8,8,-5,8,-6,8,-8,]),')':([3,12,13,14,15,16,17,18,20,],[-9,-7,-10,20,-4,-5,-3,-6,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[5,]),'expression':([0,4,6,7,8,9,10,11,],[1,12,14,15,16,17,18,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME = expression','statement',3,'p_statement_assign','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',43),
  ('statement -> expression','statement',1,'p_statement_expr','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',47),
  ('expression -> expression + expression','expression',3,'p_expression_binop','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',52),
  ('expression -> expression - expression','expression',3,'p_expression_binop','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',53),
  ('expression -> expression * expression','expression',3,'p_expression_binop','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',54),
  ('expression -> expression / expression','expression',3,'p_expression_binop','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',55),
  ('expression -> - expression','expression',2,'p_expression_uminus','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',62),
  ('expression -> ( expression )','expression',3,'p_expression_group','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',66),
  ('expression -> NUMBER','expression',1,'p_expression_number','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',70),
  ('expression -> NAME','expression',1,'p_expression_name','/home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/vhdl_toolkit/valueInterpret.py',74),
]
