from hdl_toolkit.synthetisator.interfaceLevel.interface import Interface
from hdl_toolkit.interfaces.std import Ap_none, Ap_clk
from hdl_toolkit.hdlObjects.typeShortcuts import vecT
from hdl_toolkit.hdlObjects.specialValues import DIRECTION
from hdl_toolkit.synthetisator.interfaceLevel.unit import Unit

# [TODO] this is only torso
class CameraIntf(Interface):
    """
    http://www.voti.nl/docs/OV7670.pdf p.7
    
    HREF is high when data of row are valid
    there is fall in HSYNC after each row
    VSYNC is on for a while after end of the frame (after fall in HSYNC)
    """
    def _declr(self):
        self.d = Ap_none(dtype=vecT(8))
        self.xclk = Ap_clk(masterDir=DIRECTION.IN)
        self.pclk = Ap_clk()  # pixel clock generated by master
        
        self.href = Ap_none()
        self.hsync = Ap_none()
        self.vsync = Ap_none()
        
        self.reset = Ap_none(masterDir=DIRECTION.IN)
        self.pwdn = Ap_none(masterDir=DIRECTION.IN)



class CameraToAxiStream(Unit):
    pass